export const ZONES = [
  { zoneId: 1141, zone: 'bahrain.html' },
  { zoneId: 1142, zone: 'saudi-arabia/race-result.html' },
  { zoneId: 1143, zone: 'australia/race-result.html' },
  { zoneId: 1207, zone: 'australia/race-result.html' },
  { zoneId: 1208, zone: 'miami/race-result.html' },
  { zoneId: 1209, zone: 'italy/race-result.html' },
  { zoneId: 1210, zone: 'monaco.html' },
  { zoneId: 1211, zone: 'spain/race-result.html' },
  { zoneId: 1212, zone: 'canada/race-result.html' },
  { zoneId: 1213, zone: 'austria.html' },
  { zoneId: 1214, zone: 'great-britain.html' },
  { zoneId: 1215, zone: 'hungary.html' },
  { zoneId: 1216, zone: 'belgium.html' },
  { zoneId: 1217, zone: 'netherlands.html' },
  { zoneId: 1218, zone: 'italy.html' },
  { zoneId: 1219, zone: 'singapore.html' },
  { zoneId: 1220, zone: 'japan.html' },
  { zoneId: 1221, zone: 'qatar.html' },
  { zoneId: 1222, zone: 'united-states.html' },
  { zoneId: 1223, zone: 'mexico.html' },
  { zoneId: 1224, zone: 'brazil.html' },
  { zoneId: 1225, zone: 'las-vegas.html' },
  { zoneId: 1226, zone: 'abu-dhabi.html' },
];

// export const ZONES = [
//     { zoneId: 1141, zone: 'bahrain.html', urlMore: 'https://www.formula1.com/en/results/jcr:content/resultsarchive.html/2023/races/1141/bahrain.html',},
//     { zoneId: 1142, zone: 'saudi-arabia/race-result.html', urlMore: 'https://www.formula1.com/en/results/jcr:content/resultsarchive.html/2023/races/1142/saudi-arabia/race-result.html' },
//     { zoneId: 1143, zone: 'australia/race-result.html', urlMore: 'https://www.formula1.com/en/results/jcr:content/resultsarchive.html/2023/races/1143/australia/race-result.html' },
//     { zoneId: 1207, zone: 'australia/race-result.html', urlMore: 'https://www.formula1.com/en/results/jcr:content/resultsarchive.html/2023/races/1143/australia/race-result.html' },
//     { zoneId: 1208, zone: 'miami/race-result.html', urlMore: 'https://www.formula1.com/en/results/jcr:content/resultsarchive.html/2023/races/1208/miami/race-result.html' },
//     { zoneId: 1209, zone: 'italy/race-result.html', urlMore: 'https://www.formula1.com/en/results/jcr:content/resultsarchive.html/2023/races/1209/italy/race-result.html' },
//     { zoneId: 1210, zone: 'monaco.html', urlMore: 'https://www.formula1.com/en/results/jcr:content/resultsarchive.html/2023/races/1210/monaco.html' },
//     { zoneId: 1211, zone: 'spain/race-result.html', urlMore: 'https://www.formula1.com/en/results/jcr:content/resultsarchive.html/2023/races/1211/spain/race-result.html' },
//     { zoneId: 1212, zone: 'canada/race-result.html', urlMore: 'https://www.formula1.com/en/results/jcr:content/resultsarchive.html/2023/races/1212/canada/race-result.html' },
//     { zoneId: 1213, zone: 'austria.html', urlMore: 'https://www.formula1.com/en/results/jcr:content/resultsarchive.html/2023/races/1213/austria.html' },
//     { zoneId: 1214, zone: 'great-britain.html', urlMore: 'https://www.formula1.com/en/results/jcr:content/resultsarchive.html/2023/races/1214/great-britain.html' },
//     { zoneId: 1215, zone: 'hungary.html', urlMore: 'https://www.formula1.com/en/results/jcr:content/resultsarchive.html/2023/races/1215/hungary.html' },
//     { zoneId: 1216, zone: 'belgium.html', urlMore: 'https://www.formula1.com/en/results/jcr:content/resultsarchive.html/2023/races/1216/belgium.html' },
//     { zoneId: 1217, zone: 'netherlands.html', urlMore: 'https://www.formula1.com/en/results/jcr:content/resultsarchive.html/2023/races/1217/netherlands.html' },
//     { zoneId: 1218, zone: 'italy.html', urlMore: 'https://www.formula1.com/en/results/jcr:content/resultsarchive.html/2023/races/1218/italy.html' },
//     { zoneId: 1219, zone: 'singapore.html', urlMore: 'https://www.formula1.com/en/results/jcr:content/resultsarchive.html/2023/races/1219/singapore.html' },
//     { zoneId: 1220, zone: 'japan.html', urlMore: 'https://www.formula1.com/en/results/jcr:content/resultsarchive.html/2023/races/1220/japan.html' },
//     { zoneId: 1221, zone: 'qatar.html', urlMore: 'https://www.formula1.com/en/results/jcr:content/resultsarchive.html/2023/races/1221/qatar.html' },
//     { zoneId: 1222, zone: 'united-states.html', urlMore: 'https://www.formula1.com/en/results/jcr:content/resultsarchive.html/2023/races/1222/united-states.html' },
//     { zoneId: 1223, zone: 'mexico.html', urlMore: 'https://www.formula1.com/en/results/jcr:content/resultsarchive.html/2023/races/1223/mexico.html' },
//     { zoneId: 1224, zone: 'brazil.html', urlMore: 'https://www.formula1.com/en/results/jcr:content/resultsarchive.html/2023/races/1224/brazil.html' },
//     { zoneId: 1225, zone: 'las-vegas.html', urlMore: 'https://www.formula1.com/en/results/jcr:content/resultsarchive.html/2023/races/1225/las-vegas.html' },
//     { zoneId: 1226, zone: 'abu-dhabi.html', urlMore: 'https://www.formula1.com/en/results/jcr:content/resultsarchive.html/2023/races/1226/abu-dhabi.html' },
//   ];
